sonar.projectKey=SeminarskiSoftveri
sonar.projectName=SeminarskiSoftveri
sonar.projectVersion=1.0

sonar.sourceEncoding=UTF-8

sonar.sources=Dispecer_Klijent/src,Dispecer_Server/src,Dispecer_Zajednicki/src

sonar.tests=Dispecer_Server/test

sonar.java.binaries=Dispecer_Klijent/build/classes,Dispecer_Server/build/classes,Dispecer_Zajednicki/build/classes

sonar.exclusions=**/build/**,**/dist/**,**/nbproject/**,**/*.form

sonar.coverage.exclusions=**