/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme.nalog;

import controller.ClientController;
import domen.Dispecer;
import domen.NalogZaTransportRobe;
import domen.PoslovniPartner;
import domen.Roba;
import domen.Rola;
import domen.StatusNaloga;
import domen.StavkaNaloga;
import forme.ModForme;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import modeli.stavka.ModelTabeleStavkaNaloga;
import sesija.Sesija;

/**
 *
 * @author mikir
 */
public class DodajNalogForma extends javax.swing.JFrame {

    private NalogZaTransportRobe noviNalog;
    private ModForme modForme;
    private ArrayList<StavkaNaloga> stavkeNovogNaloga;
    private PretraziNalogeForma pretrazi;

    /**
     * Creates new form DodajNalogForma
     */
    public DodajNalogForma(ModForme modForme) throws Exception {
        initComponents();
        this.modForme = modForme;
        noviNalog = new NalogZaTransportRobe();
        stavkeNovogNaloga = new ArrayList<>();
        jButtonAzuriraj.setVisible(false);
        jButtonOmoguciIzmene.setVisible(false);
        jComboBoxStatus.setEnabled(false);
        if (Sesija.getInstance().getUlogovani().getRola() == Rola.KORISNIK) {
            jComboBoxDispecer.setEnabled(false);
        }
        try {
            pripremi();
        } catch (Exception ex) {
            throw new Exception();
        }
    }

    public DodajNalogForma(PretraziNalogeForma pretrazi, NalogZaTransportRobe n, ModForme modForme) throws Exception {
        initComponents();
        this.modForme = modForme;
        this.pretrazi = pretrazi;

        noviNalog = n;
        stavkeNovogNaloga = n.getStavke();

        jButtonDodajNalog.setVisible(false);
        
        jButtonAzuriraj.setEnabled(false);

        jComboBoxStatus.setEnabled(false);
        if (Sesija.getInstance().getUlogovani().getRola() == Rola.KORISNIK) {
            jComboBoxDispecer.setEnabled(false);
        }
        try {
            pripremi();
        } catch (Exception ex) {
            throw new Exception();
        }
        
        pokupiPodatke();
        

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldDatumKreiranja = new javax.swing.JTextField();
        jTextFieldDatumIzvrsenja = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldAdresaUtovara = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldAdresaIstovara = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxStatus = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxPoslovniPartner = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxRoba = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldKolicina = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableStavke = new javax.swing.JTable();
        jButtonDodajStavku = new javax.swing.JButton();
        jButtonObrisiStavku = new javax.swing.JButton();
        jLabelDispecer = new javax.swing.JLabel();
        jComboBoxDispecer = new javax.swing.JComboBox<>();
        jButtonOdustani = new javax.swing.JButton();
        jButtonDodajNalog = new javax.swing.JButton();
        jButtonAzuriraj = new javax.swing.JButton();
        jButtonOmoguciIzmene = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Unesite podatke o nalogu:");

        jLabel2.setText("Datum kreiranja:");

        jLabel3.setText("Datum izvrsenja :");

        jLabel4.setText("Adresa utovara :");

        jLabel5.setText("Adresa istovara :");

        jLabel6.setText("Status naloga :");

        jComboBoxStatus.setModel(new DefaultComboBoxModel<>(StatusNaloga.values()));
        jComboBoxStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxStatusActionPerformed(evt);
            }
        });

        jLabel7.setText("Poslovni partner :");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Unesite podatke o stavci naloga :");

        jLabel9.setText("Roba : ");

        jLabel11.setText("Kolicina : ");

        jTableStavke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableStavke);

        jButtonDodajStavku.setText("DODAJ STAVKU");
        jButtonDodajStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDodajStavkuActionPerformed(evt);
            }
        });

        jButtonObrisiStavku.setText("OBRISI STAVKU");
        jButtonObrisiStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObrisiStavkuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(jComboBoxRoba, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(42, 42, 42)
                        .addComponent(jButtonDodajStavku)
                        .addGap(32, 32, 32)
                        .addComponent(jButtonObrisiStavku)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jComboBoxRoba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonDodajStavku)
                            .addComponent(jButtonObrisiStavku))
                        .addGap(4, 4, 4)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabelDispecer.setText("Dispecer :");

        jButtonOdustani.setText("ODUSTANI");
        jButtonOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOdustaniActionPerformed(evt);
            }
        });

        jButtonDodajNalog.setText("DODAJ NALOG");
        jButtonDodajNalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDodajNalogActionPerformed(evt);
            }
        });

        jButtonAzuriraj.setText("AZURIRAJ NALOG");

        jButtonOmoguciIzmene.setText("OMOGUCI IZMENE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonOdustani)
                        .addGap(52, 52, 52)
                        .addComponent(jButtonOmoguciIzmene)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAzuriraj)
                        .addGap(28, 28, 28)
                        .addComponent(jButtonDodajNalog)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldAdresaUtovara, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                            .addComponent(jTextFieldDatumIzvrsenja, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldDatumKreiranja, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldAdresaIstovara))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxPoslovniPartner, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxDispecer, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDispecer, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jTextFieldDatumKreiranja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jTextFieldDatumIzvrsenja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldAdresaUtovara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jTextFieldAdresaIstovara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxPoslovniPartner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelDispecer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxDispecer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel1))
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOdustani)
                    .addComponent(jButtonDodajNalog)
                    .addComponent(jButtonAzuriraj)
                    .addComponent(jButtonOmoguciIzmene))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxStatusActionPerformed

    private void jButtonOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOdustaniActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonOdustaniActionPerformed

    private void jButtonDodajStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDodajStavkuActionPerformed
        // TODO add your handling code here:
        Roba r = (Roba) jComboBoxRoba.getSelectedItem();

        if (r == null) {
            JOptionPane.showMessageDialog(this, "Morate odabrati robu!!", "UPOZORENJE", JOptionPane.WARNING_MESSAGE);
            return;
        }
        float kolicina;
        try {
            kolicina = Float.parseFloat(jTextFieldKolicina.getText().trim());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Nepravilno uneta količina! Morate uneti količinu kao decimalan broj\nNa primer: 10.4 ili 10 !!!", "UPOZORENJE", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (kolicina == 0) {
            JOptionPane.showMessageDialog(this, "Kolicina ne sme biti 0.0!!", "UPOZORENJE", JOptionPane.WARNING_MESSAGE);
            return;
        }

        StavkaNaloga novaStavka = new StavkaNaloga(noviNalog, kolicina, r);

        stavkeNovogNaloga.add(novaStavka);

        azurirajTabeluStavki();

        jComboBoxRoba.setSelectedIndex(-1);
        jTextFieldKolicina.setText("");


    }//GEN-LAST:event_jButtonDodajStavkuActionPerformed

    private void jButtonObrisiStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObrisiStavkuActionPerformed
        // TODO add your handling code here:

        int selektovaniRed = jTableStavke.getSelectedRow();

        if (selektovaniRed < 0) {
            JOptionPane.showMessageDialog(this, "Morate odabrati stavku koju zelite da obrisete!!", "UPOZORENJE", JOptionPane.WARNING_MESSAGE);
            return;
        }

        for (int i = 0; i < stavkeNovogNaloga.size(); i++) {
            if (i == selektovaniRed) {
                stavkeNovogNaloga.remove(i);
                break;
            }
        }

        azurirajTabeluStavki();

    }//GEN-LAST:event_jButtonObrisiStavkuActionPerformed

    private void jButtonDodajNalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDodajNalogActionPerformed
        // TODO add your handling code here:
        try {

            SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy.");
            sdf.setLenient(false);

            String datumKreiranjaText = jTextFieldDatumKreiranja.getText().trim();
            Date datumKreiranja = null;

            try {
                datumKreiranja = sdf.parse(datumKreiranjaText);
            } catch (ParseException pex) {
                JOptionPane.showMessageDialog(this, "Nepravilno unet datum kreiranja naloga!! Datum se mora uneti u formatu: dd.MM.yyyy.\nNa primer: 22.05.2025.", "UPOZORENJE", JOptionPane.WARNING_MESSAGE);
                return;
            }

            String datumIzvrsenjaText = jTextFieldDatumIzvrsenja.getText().trim();
            Date datumIzvrsenja = null;

            try {
                datumIzvrsenja = sdf.parse(datumIzvrsenjaText);
            } catch (ParseException pex) {
                JOptionPane.showMessageDialog(this, "Nepravilno unet datum izvrsenja naloga!! Datum se mora uneti u formatu: dd.MM.yyyy.\nNa primer: 22.05.2025.", "UPOZORENJE", JOptionPane.WARNING_MESSAGE);
                return;
            }
            Date danasnjiDatum = null;
            try {
                danasnjiDatum = sdf.parse(sdf.format(new Date()));
            } catch (ParseException ex) {
                Logger.getLogger(DodajNalogForma.class.getName()).log(Level.INFO, "Neuspesno parsiranje danasnjeg datuma...");
                return;
            }

            if (datumKreiranja.before(danasnjiDatum)) {
                JOptionPane.showMessageDialog(this, "Nepravilno unet datum kreiranja naloga!! Datum kreiranja mora biti u buducnosti!!", "UPOZORENJE", JOptionPane.WARNING_MESSAGE);
                return;
            }

            if (datumIzvrsenja.before(datumKreiranja)) {
                JOptionPane.showMessageDialog(this, "Nepravilno unet datum izvrsenja naloga!! Datum izvrsenja mora biti pre datuma kreiranja naloga!!", "UPOZORENJE", JOptionPane.WARNING_MESSAGE);
                return;
            }

            String adresaUtovara = jTextFieldAdresaUtovara.getText().trim();

            if (adresaUtovara == null || adresaUtovara.isBlank()) {
                JOptionPane.showMessageDialog(this, "Nije uneta adresa utovara!!", "GRESKA", JOptionPane.ERROR_MESSAGE);
                return;
            }

            String adressaIstovara = jTextFieldAdresaIstovara.getText().trim();

            if (adressaIstovara == null || adressaIstovara.isBlank()) {
                JOptionPane.showMessageDialog(this, "Nije uneta adresa istovara!!", "GRESKA", JOptionPane.ERROR_MESSAGE);
                return;
            }

            StatusNaloga status = (StatusNaloga) jComboBoxStatus.getSelectedItem();

            PoslovniPartner pp = (PoslovniPartner) jComboBoxPoslovniPartner.getSelectedItem();

            if (pp == null) {
                JOptionPane.showMessageDialog(this, "Nije izabran poslovni partner!!", "GRESKA", JOptionPane.ERROR_MESSAGE);
                return;
            }

            Dispecer d = (Dispecer) jComboBoxDispecer.getSelectedItem();

            noviNalog.setDispecer(d);
            noviNalog.setPoslovniPartner(pp);
            noviNalog.setAdresaUtovara(adresaUtovara);
            noviNalog.setAdresaIstovara(adressaIstovara);
            noviNalog.setDatumKreiranja(datumKreiranja);
            noviNalog.setDatumIzvrsenja(datumIzvrsenja);
            noviNalog.setStatus(status);
            noviNalog.setIdNaloga(-1);

            noviNalog.setStavke(stavkeNovogNaloga);

            if (stavkeNovogNaloga.size() == 0) {
                noviNalog.setUkupanIznosPosla(0);
            } else {
                noviNalog.izracunajUkupneTroskovePosla();
            }

            ArrayList<Integer> brojeviDodatih = ClientController.getInstance().dodajNalog(noviNalog);

            if (brojeviDodatih.get(0) > 0) {
                if (brojeviDodatih.size() == 2) {
                    if (brojeviDodatih.get(1) > 0) {
                        JOptionPane.showMessageDialog(this, "Sistem je zapamtio nalog za transport robe!!", "USPESNO", JOptionPane.INFORMATION_MESSAGE);
                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(this, "Sistem ne moze da zapamti nalog za transport robe!!", "UPOZORENJE", JOptionPane.WARNING_MESSAGE);
                        return;
                    }
                }
                JOptionPane.showMessageDialog(this, "Sistem je zapamtio nalog za transport robe!!", "USPESNO", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Sistem ne moze da zapamti nalog za transport robe!!", "UPOZORENJE", JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da zapamti nalog za transport robe!!", "UPOZORENJE", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_jButtonDodajNalogActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAzuriraj;
    private javax.swing.JButton jButtonDodajNalog;
    private javax.swing.JButton jButtonDodajStavku;
    private javax.swing.JButton jButtonObrisiStavku;
    private javax.swing.JButton jButtonOdustani;
    private javax.swing.JButton jButtonOmoguciIzmene;
    private javax.swing.JComboBox<Dispecer> jComboBoxDispecer;
    private javax.swing.JComboBox<PoslovniPartner> jComboBoxPoslovniPartner;
    private javax.swing.JComboBox<Roba> jComboBoxRoba;
    private javax.swing.JComboBox<StatusNaloga> jComboBoxStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelDispecer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableStavke;
    private javax.swing.JTextField jTextFieldAdresaIstovara;
    private javax.swing.JTextField jTextFieldAdresaUtovara;
    private javax.swing.JTextField jTextFieldDatumIzvrsenja;
    private javax.swing.JTextField jTextFieldDatumKreiranja;
    private javax.swing.JTextField jTextFieldKolicina;
    // End of variables declaration//GEN-END:variables

    private void pripremi() throws Exception {
        ArrayList<PoslovniPartner> partneri;
        ArrayList<Dispecer> dispeceri;
        ArrayList<Roba> roba;

        try {
            partneri = ClientController.getInstance().getPoslovniPartneri();

            for (PoslovniPartner partner : partneri) {
                jComboBoxPoslovniPartner.addItem(partner);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Nisu ucitani partneri!!", "GRESKA", JOptionPane.ERROR_MESSAGE);
            throw new Exception();
        }

        try {
            dispeceri = ClientController.getInstance().getDispeceri();

            for (Dispecer dispecer : dispeceri) {
                jComboBoxDispecer.addItem(dispecer);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Nisu ucitani dispeceri!!", "GRESKA", JOptionPane.ERROR_MESSAGE);
            throw new Exception();
        }

        try {
            roba = ClientController.getInstance().getRoba();

            for (Roba r : roba) {
                jComboBoxRoba.addItem(r);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Nije ucitana roba!!", "GRESKA", JOptionPane.ERROR_MESSAGE);
            throw new Exception();
        }

        ArrayList<StavkaNaloga> listaStavki = new ArrayList<>();

        ModelTabeleStavkaNaloga mts = new ModelTabeleStavkaNaloga(listaStavki);
        jTableStavke.setModel(mts);

        //Predefinisi ulogovanog korisnika
        jComboBoxDispecer.setSelectedItem(Sesija.getInstance().getUlogovani());
//        for (Dispecer dispecer : dispeceri) {
//            if(dispecer.equals(Sesija.getInstance().getUlogovani())){
//                jComboBoxDispecer.setSelectedItem(dispecer);
//            }
//        }
        jComboBoxPoslovniPartner.setSelectedIndex(-1);
        jComboBoxRoba.setSelectedIndex(-1);

    }

    private void azurirajTabeluStavki() {
        ModelTabeleStavkaNaloga mts = new ModelTabeleStavkaNaloga(stavkeNovogNaloga);
        jTableStavke.setModel(mts);
    }

    private void pokupiPodatke() {
        jTextFieldDatumKreiranja.setText(new SimpleDateFormat("dd.MM.yyy.").format(noviNalog.getDatumKreiranja()));
        jTextFieldDatumKreiranja.setEnabled(false);
        
        jTextFieldDatumIzvrsenja.setText(new SimpleDateFormat("dd.MM.yyy.").format(noviNalog.getDatumIzvrsenja()));
        jTextFieldDatumIzvrsenja.setEnabled(false);
        
        jTextFieldAdresaUtovara.setText(noviNalog.getAdresaUtovara());
        jTextFieldAdresaIstovara.setText(noviNalog.getAdresaIstovara());
        
        jTextFieldAdresaUtovara.setEnabled(false);
        jTextFieldAdresaIstovara.setEnabled(false);
        
        jComboBoxStatus.setSelectedItem(noviNalog.getStatus());
        
        jComboBoxPoslovniPartner.setSelectedItem(noviNalog.getPoslovniPartner());
        jComboBoxPoslovniPartner.setEnabled(false);
        
        jComboBoxDispecer.setSelectedItem(noviNalog.getDispecer());
        jComboBoxDispecer.setEnabled(false);
        
        jButtonDodajStavku.setEnabled(false);
        jButtonObrisiStavku.setEnabled(false);
        
        jComboBoxRoba.setEnabled(false);
        jTextFieldKolicina.setEnabled(false);
        
        ModelTabeleStavkaNaloga mts = new ModelTabeleStavkaNaloga(noviNalog.getStavke());
        jTableStavke.setModel(mts);
        
        jTableStavke.setEnabled(false);
    }
}
