/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme.nalog;

import controller.ClientController;
import domen.Dispecer;
import domen.Mesto;
import domen.NalogZaTransportRobe;
import domen.PoslovniPartner;
import domen.Roba;
import domen.Rola;
import domen.StatusNaloga;
import domen.StavkaNaloga;
import forme.ModForme;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import modeli.nalog.ModelTabelePrikaziNaloge;
import sesija.Sesija;

/**
 *
 * @author mikir
 */
public class PretraziNalogeForma extends javax.swing.JFrame {

    private ArrayList<NalogZaTransportRobe> nalozi = new ArrayList<>();
    private DodajNalogForma dnf;

    /**
     * Creates new form PretraziNalogeForma
     */
    public PretraziNalogeForma() throws Exception {
        initComponents();
        setTitle("PRETRAGA NALOGA");
        setLocationRelativeTo(null);
        try {
            postaviTabelu();
            pripremiFormu();
        } catch (Exception ex) {
            throw new Exception();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxDispecer = new javax.swing.JComboBox<>();
        jComboBoxRoba = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldDatumUtovara = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldDatumIstovara = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxStatus = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldPIBpartnera = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldNazivPartnera = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButtonOdustani = new javax.swing.JButton();
        jButtonPrikazi = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableNalozi = new javax.swing.JTable();
        jButtonFiltriraj = new javax.swing.JButton();
        jRadioButtonNalog = new javax.swing.JRadioButton();
        jRadioButtonPartner = new javax.swing.JRadioButton();
        jRadioButtonRoba = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldMesto = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldDrzava = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Podaci o nalogu");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Podaci o dispeceru:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Podaci o poslovnom partneru:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Podaci o robi:");

        jLabel5.setText("Datum utovara:");

        jLabel6.setText("Datum istovara:");

        jLabel7.setText("Status:");

        jComboBoxStatus.setModel(new DefaultComboBoxModel<>(StatusNaloga.values()));

        jLabel8.setText("Naziv partnera:");

        jLabel9.setText("PIB partnera:");

        jLabel10.setText("Dispecer:");

        jLabel11.setText("Roba:");

        jButtonOdustani.setText("ODUSTANI");
        jButtonOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOdustaniActionPerformed(evt);
            }
        });

        jButtonPrikazi.setText("PRIKAZI INFORMACIJE O NALOGU");
        jButtonPrikazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrikaziActionPerformed(evt);
            }
        });

        jTableNalozi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableNalozi);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButtonFiltriraj.setText("FILTRIRAJ");
        jButtonFiltriraj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFiltrirajActionPerformed(evt);
            }
        });

        jRadioButtonNalog.setText("Filtriraj prema nalogu");
        jRadioButtonNalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonNalogActionPerformed(evt);
            }
        });

        jRadioButtonPartner.setText("Filtiraj prema poslovnom partneru");
        jRadioButtonPartner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPartnerActionPerformed(evt);
            }
        });

        jRadioButtonRoba.setText("Filtiraj prema robi");
        jRadioButtonRoba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonRobaActionPerformed(evt);
            }
        });

        jLabel12.setText("Naziv mesta:");

        jLabel13.setText("Drzava:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(143, 143, 143))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonNalog)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(jRadioButtonRoba)
                        .addGap(46, 46, 46)
                        .addComponent(jRadioButtonPartner)))
                .addGap(207, 207, 207))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonOdustani)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonPrikazi)
                .addGap(16, 16, 16))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldDatumUtovara, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldDatumIstovara, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(35, 35, 35)
                                        .addComponent(jComboBoxDispecer, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addComponent(jLabel2)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(268, 268, 268)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jComboBoxRoba, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(200, 200, 200)
                                        .addComponent(jLabel11)))))
                        .addGap(68, 68, 68)
                        .addComponent(jButtonFiltriraj))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(561, 561, 561)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel13)
                                .addComponent(jLabel12)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextFieldNazivPartnera)
                                        .addComponent(jTextFieldPIBpartnera, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTextFieldMesto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldDrzava, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTextFieldNazivPartnera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldPIBpartnera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldMesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldDatumUtovara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldDatumIstovara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDrzava, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonFiltriraj)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxRoba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxDispecer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonPartner)
                    .addComponent(jRadioButtonRoba)
                    .addComponent(jRadioButtonNalog))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOdustani)
                    .addComponent(jButtonPrikazi))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOdustaniActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonOdustaniActionPerformed

    private void jRadioButtonNalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNalogActionPerformed
        // TODO add your handling code here:

        jTextFieldDatumIstovara.setEnabled(true);
        jTextFieldDatumUtovara.setEnabled(true);
        jComboBoxStatus.setEnabled(true);

        jComboBoxStatus.setSelectedIndex(-1);

        jTextFieldNazivPartnera.setEnabled(false);
        jTextFieldPIBpartnera.setEnabled(false);
        jTextFieldMesto.setEnabled(false);
        jTextFieldDrzava.setEnabled(false);

        jComboBoxRoba.setEnabled(false);

        if (Sesija.getInstance().getUlogovani().getRola() == Rola.ADMINISTRATOR) {
            jComboBoxDispecer.setEnabled(true);
            jComboBoxDispecer.setSelectedIndex(-1);
//            jComboBoxDispecer.setSelectedItem(Sesija.getInstance().getUlogovani());
        } else {
            jComboBoxDispecer.setEnabled(false);
            jComboBoxDispecer.setSelectedItem(Sesija.getInstance().getUlogovani());
        }
//        jComboBoxDispecer.setSelectedItem(Sesija.getInstance().getUlogovani());

    }//GEN-LAST:event_jRadioButtonNalogActionPerformed

    private void jRadioButtonRobaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonRobaActionPerformed
        // TODO add your handling code here:

        jTextFieldNazivPartnera.setEnabled(false);
        jTextFieldPIBpartnera.setEnabled(false);
        jTextFieldMesto.setEnabled(false);
        jTextFieldDrzava.setEnabled(false);

        jTextFieldDatumIstovara.setEnabled(false);
        jTextFieldDatumUtovara.setEnabled(false);
        jComboBoxStatus.setEnabled(false);

        jComboBoxDispecer.setEnabled(false);

        jComboBoxRoba.setEnabled(true);
        jComboBoxRoba.setSelectedIndex(-1);

    }//GEN-LAST:event_jRadioButtonRobaActionPerformed

    private void jRadioButtonPartnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPartnerActionPerformed
        // TODO add your handling code here:

        jTextFieldDatumIstovara.setEnabled(false);
        jTextFieldDatumUtovara.setEnabled(false);
        jComboBoxStatus.setEnabled(false);

        jComboBoxRoba.setEnabled(false);

        jComboBoxDispecer.setEnabled(false);

        jTextFieldNazivPartnera.setEnabled(true);
        jTextFieldPIBpartnera.setEnabled(true);
        jTextFieldMesto.setEnabled(true);
        jTextFieldDrzava.setEnabled(true);
    }//GEN-LAST:event_jRadioButtonPartnerActionPerformed

    private void jButtonFiltrirajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFiltrirajActionPerformed
        NalogZaTransportRobe nalog = new NalogZaTransportRobe();
        try {

            if (jRadioButtonNalog.isSelected()) {
                SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy.");
                sdf.setLenient(false);

                String datumUtovaraText = jTextFieldDatumUtovara.getText().trim();
                Date datumUtovara = null;
                if (datumUtovaraText != null && !datumUtovaraText.isBlank()) {
                    try {
                        datumUtovara = sdf.parse(datumUtovaraText);
                    } catch (ParseException pex) {
                        JOptionPane.showMessageDialog(this, "Nepravilno unet datum utovara!! Datum se mora uneti u formatu: dd.MM.yyyy.\nNa primer: 22.05.2025.", "UPOZORENJE", JOptionPane.WARNING_MESSAGE);
                        return;
                    }
                }

                String datumIstovaraText = jTextFieldDatumIstovara.getText().trim();
                Date datumIstovara = null;

                if (datumIstovaraText != null && !datumIstovaraText.isBlank()) {
                    try {
                        datumIstovara = sdf.parse(datumIstovaraText);
                    } catch (ParseException pex) {
                        JOptionPane.showMessageDialog(this, "Nepravilno unet datum istovara!! Datum se mora uneti u formatu: dd.MM.yyyy.\nNa primer: 22.05.2025.", "UPOZORENJE", JOptionPane.WARNING_MESSAGE);
                        return;
                    }
                }

                StatusNaloga status = (StatusNaloga) jComboBoxStatus.getSelectedItem();

                Dispecer d = (Dispecer) jComboBoxDispecer.getSelectedItem();

                nalog.setDatumUtovara(datumUtovara);
                nalog.setDatumIstovara(datumIstovara);
                nalog.setStatus(status);
                nalog.setDispecer(d);

                if (Sesija.getInstance().getUlogovani().getRola() == Rola.ADMINISTRATOR) {
                    jComboBoxDispecer.setSelectedIndex(-1);
                }

                jComboBoxStatus.setSelectedIndex(-1);

                jTextFieldDatumUtovara.setText("");
                jTextFieldDatumIstovara.setText("");

            }
//
            if (jRadioButtonPartner.isSelected()) {

                PoslovniPartner pp = new PoslovniPartner();

                String nazivPartnera = jTextFieldNazivPartnera.getText().trim();
                String pib = jTextFieldPIBpartnera.getText().trim();

                Mesto m = new Mesto();
                String nazivMesta = jTextFieldMesto.getText().trim();
                String drzava = jTextFieldDrzava.getText().trim();
                m.setDrzava(drzava);
                m.setNazivMesta(nazivMesta);

                pp.setMesto(m);
                pp.setNazivPartnera(nazivPartnera);
                pp.setPib(pib);

                nalog.setPoslovniPartner(pp);

                if (Sesija.getInstance().getUlogovani().getRola() == Rola.KORISNIK) {
                    nalog.setDispecer((Dispecer) jComboBoxDispecer.getSelectedItem());
                }
                
                jTextFieldMesto.setText("");
                jTextFieldNazivPartnera.setText("");
                jTextFieldPIBpartnera.setText("");
                jTextFieldDrzava.setText("");
            }

            if (jRadioButtonRoba.isSelected()) {
                ArrayList<StavkaNaloga> stavke = new ArrayList<>();

                StavkaNaloga stavka = new StavkaNaloga();

                Roba r = (Roba) jComboBoxRoba.getSelectedItem();
                stavka.setRoba(r);

                stavke.add(stavka);

                nalog.setStavke(stavke);

                if (Sesija.getInstance().getUlogovani().getRola() == Rola.KORISNIK) {
                    nalog.setDispecer((Dispecer) jComboBoxDispecer.getSelectedItem());
                }
                
                jComboBoxRoba.setSelectedIndex(-1);
            }

            ArrayList<NalogZaTransportRobe> pretrazeniNalozi = ClientController.getInstance().filtrirajNaloge(nalog);

            JOptionPane.showMessageDialog(this, "Sistem je nasao naloge za transport robe po zadatim kriterijumima!", "USPESNO", JOptionPane.INFORMATION_MESSAGE);

            ModelTabelePrikaziNaloge mt = new ModelTabelePrikaziNaloge(pretrazeniNalozi);
            jTableNalozi.setModel(mt);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da nadje naloge za transport robe po zadatim kriterijumima!", "UPOZORENJE", JOptionPane.WARNING_MESSAGE);
            postaviPraznuTabelu();

        }
    }//GEN-LAST:event_jButtonFiltrirajActionPerformed

    private void jButtonPrikaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrikaziActionPerformed
        int selectedIndex = jTableNalozi.getSelectedRow();
        if (selectedIndex < 0) {
            JOptionPane.showMessageDialog(this, "Morate odabrati nalog koji zelite da pogledate!", "UPOZORENJE", JOptionPane.WARNING_MESSAGE);
            return;
        }

        ModelTabelePrikaziNaloge mtp = (ModelTabelePrikaziNaloge) jTableNalozi.getModel();
        NalogZaTransportRobe n = mtp.getLista().get(selectedIndex);

        if (dnf == null || !dnf.isVisible()) {
            try {
                dnf = new DodajNalogForma(this, n, ModForme.PROMENI);
            } catch (Exception ex) {
                return;
            }
            JOptionPane.showMessageDialog(this, "Sistem je nasao nalog za transport robe!", "GRESKA", JOptionPane.INFORMATION_MESSAGE);
            dnf.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da nadje nalog za transport robe!", "GRESKA", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonPrikaziActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonFiltriraj;
    private javax.swing.JButton jButtonOdustani;
    private javax.swing.JButton jButtonPrikazi;
    private javax.swing.JComboBox<Dispecer> jComboBoxDispecer;
    private javax.swing.JComboBox<Roba> jComboBoxRoba;
    private javax.swing.JComboBox<StatusNaloga> jComboBoxStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonNalog;
    private javax.swing.JRadioButton jRadioButtonPartner;
    private javax.swing.JRadioButton jRadioButtonRoba;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableNalozi;
    private javax.swing.JTextField jTextFieldDatumIstovara;
    private javax.swing.JTextField jTextFieldDatumUtovara;
    private javax.swing.JTextField jTextFieldDrzava;
    private javax.swing.JTextField jTextFieldMesto;
    private javax.swing.JTextField jTextFieldNazivPartnera;
    private javax.swing.JTextField jTextFieldPIBpartnera;
    // End of variables declaration//GEN-END:variables

    public void postaviTabelu() throws Exception {
        try {
            NalogZaTransportRobe nalog = new NalogZaTransportRobe();
            nalog.setIdNaloga(-1);
            nalog.setDispecer(Sesija.getInstance().getUlogovani());

            nalozi = ClientController.getInstance().getNalozi(nalog);
//            if (Sesija.getInstance().getUlogovani().getRola() == Rola.ADMINISTRATOR) {
//                nalozi = ClientController.getInstance().getNaloziZaSve();
//            } else {
//                NalogZaTransportRobe nalog = new NalogZaTransportRobe();
//                nalog.setDispecer(Sesija.getInstance().getUlogovani());
//
//                nalozi = ClientController.getInstance().getNaloziZaUlogovanog(nalog);
//            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Nisu uspesno vraceni nalozi!!", "GRESKA", JOptionPane.ERROR_MESSAGE);
            throw new Exception();
        }

        ModelTabelePrikaziNaloge mtp = new ModelTabelePrikaziNaloge(nalozi);
        jTableNalozi.setModel(mtp);
    }

    private void pripremiFormu() throws Exception {

        buttonGroup1.add(jRadioButtonNalog);
        buttonGroup1.add(jRadioButtonPartner);
        buttonGroup1.add(jRadioButtonRoba);

        ArrayList<Dispecer> dispeceri;
        ArrayList<Roba> roba;

        try {
            dispeceri = ClientController.getInstance().getDispeceri();

            for (Dispecer dispecer : dispeceri) {
                jComboBoxDispecer.addItem(dispecer);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Nisu ucitani dispeceri!!", "GRESKA", JOptionPane.ERROR_MESSAGE);
            throw new Exception();
        }

        try {
            roba = ClientController.getInstance().getRoba();

            for (Roba r : roba) {
                jComboBoxRoba.addItem(r);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Nije ucitana roba!!", "GRESKA", JOptionPane.ERROR_MESSAGE);
            throw new Exception();
        }

        jComboBoxStatus.setSelectedIndex(-1);
//        jComboBoxDispecer.setSelectedIndex(-1);
        jComboBoxRoba.setSelectedIndex(-1);

        jRadioButtonNalog.doClick();
    }

    private void postaviPraznuTabelu() {
        ModelTabelePrikaziNaloge mtp = new ModelTabelePrikaziNaloge();
        jTableNalozi.setModel(mtp);
    }
}
