/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme.partner;

import controller.ClientController;
import domen.Mesto;
import domen.PoslovniPartner;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import forme.ModForme;
import modeli.ModelTabelePrikaziPoslovnePartnere;

/**
 *
 * @author mikir
 */
public class DodajPartneraForma extends javax.swing.JFrame {

    private PoslovniPartner noviPartner;
    private PretraziPoslovnogPartnera pretraziForma;

    /**
     * Creates new form DodajPartneraForma
     */
    public DodajPartneraForma(ModForme mod) throws Exception {
        initComponents();
        jButtonAzuriraj.setVisible(false);
        try {
            popuniMesto();
        } catch (Exception ex) {
            throw new Exception();
        }

    }

    public DodajPartneraForma(PretraziPoslovnogPartnera pretrazi, PoslovniPartner partner, ModForme mod) throws Exception {
        initComponents();
        jButtonDodaj.setVisible(false);

        noviPartner = partner;
        pretraziForma = pretrazi;

        jTextFieldNaziv.setText(partner.getNazivPartnera());
        jTextFieldEmail.setText(partner.getEmailPartnera());
        jTextFieldPib.setText(partner.getPib());
        jTextFieldAdresa.setText(partner.getAdresaPartnera());
        try {
            popuniMesto();
        } catch (Exception ex) {
            throw new Exception();
        }

        jComboBoxMesto.setSelectedItem(partner.getMesto());

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldNaziv = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldPib = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldAdresa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxMesto = new javax.swing.JComboBox<>();
        jButtonDodaj = new javax.swing.JButton();
        jButtonOdustani = new javax.swing.JButton();
        jButtonAzuriraj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Naziv partnera : ");

        jLabel2.setText("PIB partnera : ");

        jLabel3.setText("Adresa partnera : ");

        jLabel4.setText("Unesite podatke o poslovnom partneru");

        jLabel5.setText("Email partnera : ");

        jLabel6.setText("Mesto :");

        jButtonDodaj.setText("DODAJ PARTNERA");
        jButtonDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDodajActionPerformed(evt);
            }
        });

        jButtonOdustani.setText("ODUSTANI");
        jButtonOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOdustaniActionPerformed(evt);
            }
        });

        jButtonAzuriraj.setText("AZURIRAJ");
        jButtonAzuriraj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAzurirajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonOdustani)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAzuriraj)
                        .addGap(69, 69, 69)
                        .addComponent(jButtonDodaj))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldAdresa)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldPib, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxMesto, 0, 144, Short.MAX_VALUE))
                            .addComponent(jTextFieldEmail))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel4)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldPib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBoxMesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldAdresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDodaj)
                    .addComponent(jButtonOdustani)
                    .addComponent(jButtonAzuriraj))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOdustaniActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonOdustaniActionPerformed

    private void jButtonDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDodajActionPerformed
        try {
            noviPartner = new PoslovniPartner();

            String nazivPartnera = jTextFieldNaziv.getText().trim();

            if (nazivPartnera == null || nazivPartnera.isBlank()) {
                JOptionPane.showMessageDialog(this, "Niste uneli naziv partnera!!", "GRESKA", JOptionPane.ERROR_MESSAGE);
                return;
            }

            String pib = jTextFieldPib.getText().trim();

            if (pib == null) {
                return;
            }

            if (!pib.isBlank()) {
                if (pib.length() != 9) {
                    JOptionPane.showMessageDialog(this, "PIB moze imati tacno 9 cifara!!", "GRESKA", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                for (char c : pib.toCharArray()) {
                    if (!Character.isDigit(c)) {
                        JOptionPane.showMessageDialog(this, "PIB sme da sadrzi samo cifre!!", "GRESKA", JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                }

            }

            String adresaPartnera = jTextFieldAdresa.getText().trim();

            if (adresaPartnera == null || adresaPartnera.isBlank()) {
                JOptionPane.showMessageDialog(this, "Niste uneli adresu partnera!!", "GRESKA", JOptionPane.ERROR_MESSAGE);
                return;
            }

            String emailPartnera = jTextFieldEmail.getText().trim();

            if (emailPartnera == null || emailPartnera.isBlank()) {
                JOptionPane.showMessageDialog(this, "Niste uneli email partnera!!", "GRESKA", JOptionPane.ERROR_MESSAGE);
                return;
            }

            Mesto mesto = (Mesto) jComboBoxMesto.getSelectedItem();

            noviPartner.setNazivPartnera(nazivPartnera);
            noviPartner.setAdresaPartnera(adresaPartnera);
            noviPartner.setEmailPartnera(emailPartnera);
            noviPartner.setMesto(mesto);
            noviPartner.setPib(pib);
            noviPartner.setIdPoslovnogPartnera(-1);

            boolean uspesno = ClientController.getInstance().dodajPartnera(noviPartner);
            if (uspesno) {
                JOptionPane.showMessageDialog(this, "Sistem je zapamtio poslovnog partnera!!", "USPESNO", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Sistem ne moze da zapamti poslovnog partnera!!", "UPOZORENJE", JOptionPane.WARNING_MESSAGE);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da zapamti poslovnog partnera!!", "UPOZORENJE", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_jButtonDodajActionPerformed

    private void jButtonAzurirajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAzurirajActionPerformed

        try {
            String nazivPartnera = jTextFieldNaziv.getText().trim();

            if (nazivPartnera == null || nazivPartnera.isBlank()) {
                JOptionPane.showMessageDialog(this, "Niste uneli naziv partnera!!", "GRESKA", JOptionPane.ERROR_MESSAGE);
                return;
            }

            String pib = jTextFieldPib.getText().trim();

            if (pib == null) {
                return;
            }

            if (!pib.isBlank()) {
                if (pib.length() != 9) {
                    JOptionPane.showMessageDialog(this, "PIB moze imati tacno 9 cifara!!", "GRESKA", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                for (char c : pib.toCharArray()) {
                    if (!Character.isDigit(c)) {
                        JOptionPane.showMessageDialog(this, "PIB sme da sadrzi samo cifre!!", "GRESKA", JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                }

            }

            String adresaPartnera = jTextFieldAdresa.getText().trim();

            if (adresaPartnera == null || adresaPartnera.isBlank()) {
                JOptionPane.showMessageDialog(this, "Niste uneli adresu partnera!!", "GRESKA", JOptionPane.ERROR_MESSAGE);
                return;
            }

            String emailPartnera = jTextFieldEmail.getText().trim();

            if (emailPartnera == null || emailPartnera.isBlank()) {
                JOptionPane.showMessageDialog(this, "Niste uneli email partnera!!", "GRESKA", JOptionPane.ERROR_MESSAGE);
                return;
            }

            Mesto mesto = (Mesto) jComboBoxMesto.getSelectedItem();

            noviPartner.setNazivPartnera(nazivPartnera);
            noviPartner.setAdresaPartnera(adresaPartnera);
            noviPartner.setEmailPartnera(emailPartnera);
            noviPartner.setMesto(mesto);
            noviPartner.setPib(pib);

            boolean uspesno = ClientController.getInstance().azurirajPartnera(noviPartner);
            if (uspesno) {
                JOptionPane.showMessageDialog(this, "Sistem je zapamtio poslovnog partnera!!", "USPESNO", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
                ModelTabelePrikaziPoslovnePartnere model = (ModelTabelePrikaziPoslovnePartnere) pretraziForma.getTabela().getModel();
                model.fireTableDataChanged();
            } else {
                JOptionPane.showMessageDialog(this, "Sistem ne moze da zapamti poslovnog partnera!!", "UPOZORENJE", JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da zapamti poslovnog partnera!!", "UPOZORENJE", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_jButtonAzurirajActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAzuriraj;
    private javax.swing.JButton jButtonDodaj;
    private javax.swing.JButton jButtonOdustani;
    private javax.swing.JComboBox<Mesto> jComboBoxMesto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextFieldAdresa;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldNaziv;
    private javax.swing.JTextField jTextFieldPib;
    // End of variables declaration//GEN-END:variables

    private void popuniMesto() throws Exception {
        ArrayList<Mesto> mesta;

        try {
            mesta = ClientController.getInstance().getMesta();

            for (Mesto mesto : mesta) {
                jComboBoxMesto.addItem(mesto);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Nisu ucitana mesta!!", "GRESKA", JOptionPane.ERROR_MESSAGE);
            throw new Exception();
        }

    }
}
