/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme.partner;

import controller.ClientController;
import domen.Mesto;
import domen.NalogZaTransportRobe;
import domen.PoslovniPartner;
import forme.ModForme;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import modeli.partner.ModelTabelePrikaziPoslovnePartnere;

/**
 *
 * @author mikir
 */
public class PretraziPoslovnogPartnera extends javax.swing.JFrame {

    private ArrayList<PoslovniPartner> partneri = new ArrayList<>();
    private JTable tabela;
    private DodajPartneraForma dpf;

    /**
     * Creates new form PretraziPoslovnogPartnera
     */
    public PretraziPoslovnogPartnera() throws Exception {
        initComponents();
        setLocationRelativeTo(null);
        try {
            postaviTabelu();
        } catch (Exception ex) {
            throw new Exception();
        }
//        jRadioButtonPartner.doClick();
        tabela = jTablePartneri;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePartneri = new javax.swing.JTable();
        jButtonOdustani = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNazivPartnera = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldPib = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNazivMesta = new javax.swing.JTextField();
        jTextFieldDrzava = new javax.swing.JTextField();
        jButtonFiltriraj = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButtonpPrikazi = new javax.swing.JButton();
        jButtonObrisi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTablePartneri.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTablePartneri);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 717, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButtonOdustani.setText("ODUSTANI");
        jButtonOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOdustaniActionPerformed(evt);
            }
        });

        jLabel1.setText("Naziv partnera : ");

        jTextFieldNazivPartnera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNazivPartneraActionPerformed(evt);
            }
        });

        jLabel2.setText("PIB partnera : ");

        jLabel3.setText("Naziv mesta:");

        jLabel4.setText("Drzava : ");

        jTextFieldNazivMesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNazivMestaActionPerformed(evt);
            }
        });

        jButtonFiltriraj.setText("FILTRIRAJ");
        jButtonFiltriraj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFiltrirajActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Podaci o poslovnom partneru :");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Podaci o mestu :");

        jButtonpPrikazi.setText("PRIKAZI INFORMACIJE  O PARTNERU");
        jButtonpPrikazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonpPrikaziActionPerformed(evt);
            }
        });

        jButtonObrisi.setText("OBRISI");
        jButtonObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObrisiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jButtonOdustani)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonpPrikazi))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonObrisi))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(jLabel6)))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNazivPartnera, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))
                                        .addGap(24, 24, 24))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldPib)
                                    .addComponent(jTextFieldNazivMesta)
                                    .addComponent(jTextFieldDrzava, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonFiltriraj)))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jButtonFiltriraj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonObrisi))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldNazivPartnera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldPib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel5)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jTextFieldNazivMesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jTextFieldDrzava, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jButtonOdustani)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonpPrikazi)
                        .addGap(26, 26, 26))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOdustaniActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonOdustaniActionPerformed

    private void jTextFieldNazivPartneraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNazivPartneraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNazivPartneraActionPerformed

    private void jTextFieldNazivMestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNazivMestaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNazivMestaActionPerformed

    private void jButtonFiltrirajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFiltrirajActionPerformed
        try {
            PoslovniPartner pp = new PoslovniPartner();

//            if (jRadioButtonPartner.isSelected()) {
//                String nazivPartnera = jTextFieldNazivPartnera.getText().trim();
//                String pib = jTextFieldPib.getText().trim();
//
//                pp.setNazivPartnera(nazivPartnera);
//                pp.setPib(pib);
//            }
//
//            if (jRadioButtonMesto.isSelected()) {
//                Mesto m = new Mesto();
//                String nazivMesta = jTextFieldNazivMesta.getText().trim();
//                String drzava = jTextFieldDrzava.getText().trim();
//                m.setDrzava(drzava);
//                m.setNazivMesta(nazivMesta);
//
//                pp.setMesto(m);
//            }
            String nazivPartnera = jTextFieldNazivPartnera.getText().trim();
            String pib = jTextFieldPib.getText().trim();

            pp.setNazivPartnera(nazivPartnera);
            pp.setPib(pib);

            Mesto m = new Mesto();
            String nazivMesta = jTextFieldNazivMesta.getText().trim();
            String drzava = jTextFieldDrzava.getText().trim();
            m.setDrzava(drzava);
            m.setNazivMesta(nazivMesta);

            pp.setMesto(m);

            ArrayList<PoslovniPartner> partneriPretrazeni = ClientController.getInstance().filtrirajPartnere(pp);

            JOptionPane.showMessageDialog(this, "Sistem je nasao poslovne partnere po zadatim kriterijumima!", "USPESNO", JOptionPane.INFORMATION_MESSAGE);

            ModelTabelePrikaziPoslovnePartnere mt = new ModelTabelePrikaziPoslovnePartnere(partneriPretrazeni);
            jTablePartneri.setModel(mt);

            //JOptionPane.showMessageDialog(this, "Sistem je nasao poslovnog partnera!", "GRESKA", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da nadje poslovne partnere po zadatim kriterijumima!", "UPOZORENJE", JOptionPane.WARNING_MESSAGE);
            postaviPraznuTabelu();
            //JOptionPane.showMessageDialog(this, "Sistem ne moze da nadje poslovnog partnera!", "GRESKA", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonFiltrirajActionPerformed

    private void jButtonpPrikaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonpPrikaziActionPerformed
        int selectedIndex = jTablePartneri.getSelectedRow();
        if (selectedIndex < 0) {
            JOptionPane.showMessageDialog(this, "Morate odabrati poslovnog partnera kog zelite da pogledate!", "UPOZORENJE", JOptionPane.WARNING_MESSAGE);
            return;
        }

        ModelTabelePrikaziPoslovnePartnere mtp = (ModelTabelePrikaziPoslovnePartnere) jTablePartneri.getModel();
        PoslovniPartner pp = mtp.getLista().get(selectedIndex);
        
        if (dpf == null || !dpf.isVisible()) {
            try {
                dpf = new DodajPartneraForma(this, pp, ModForme.PROMENI);
            } catch (Exception ex) {
                return;
            }
            JOptionPane.showMessageDialog(this, "Sistem je nasao poslovnog partnera!", "GRESKA", JOptionPane.INFORMATION_MESSAGE);
            dpf.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da nadje poslovnog partnera!", "GRESKA", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_jButtonpPrikaziActionPerformed

    private void jButtonObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObrisiActionPerformed
        try {
            int selectedIndex = jTablePartneri.getSelectedRow();
            if (selectedIndex < 0) {
                JOptionPane.showMessageDialog(this, "Morate odabrati predmet za brisanje!", "UPOZORENJE", JOptionPane.WARNING_MESSAGE);
                return;
            }
            ModelTabelePrikaziPoslovnePartnere mtp = (ModelTabelePrikaziPoslovnePartnere) jTablePartneri.getModel();
            PoslovniPartner pp = mtp.getLista().get(selectedIndex);

            boolean uspesno = ClientController.getInstance().obrisiPartnera(pp);
            if (uspesno) {
                JOptionPane.showMessageDialog(this, "Sistem je obrisao poslovnog partnera!!", "USPESNO", JOptionPane.INFORMATION_MESSAGE);
                postaviTabelu();
            } else {
                JOptionPane.showMessageDialog(this, "Sistem ne moze da obrise poslovnog partnera!!", "UPOZORENJE", JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da obrise poslovnog partnera!!", "UPOZORENJE", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_jButtonObrisiActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonFiltriraj;
    private javax.swing.JButton jButtonObrisi;
    private javax.swing.JButton jButtonOdustani;
    private javax.swing.JButton jButtonpPrikazi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePartneri;
    private javax.swing.JTextField jTextFieldDrzava;
    private javax.swing.JTextField jTextFieldNazivMesta;
    private javax.swing.JTextField jTextFieldNazivPartnera;
    private javax.swing.JTextField jTextFieldPib;
    // End of variables declaration//GEN-END:variables

    public void postaviTabelu() throws Exception {
        try {
            partneri = ClientController.getInstance().getPoslovniPartneri();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Nisu uspesno vraceni poslovni partneri!!", "GRESKA", JOptionPane.ERROR_MESSAGE);
            throw new Exception();
        }

        ModelTabelePrikaziPoslovnePartnere mt = new ModelTabelePrikaziPoslovnePartnere(partneri);
        jTablePartneri.setModel(mt);
    }

    public JTable getTabela() {
        return tabela;
    }

    private void postaviPraznuTabelu() {
        ModelTabelePrikaziPoslovnePartnere mtp = new ModelTabelePrikaziPoslovnePartnere();
        jTablePartneri.setModel(mtp);
    }

}
